services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-balance
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_logs:/var/log/postgresql
    ports:
      - '5432:5432'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  postgres_data:
  redis_data:
